"use client";

import {
  ArrowDown,
  ArrowUp,
  Check,
  ChevronDown,
  Copy,
  Download,
  Eraser,
  Keyboard,
  Plus,
  Search,
  Trash2,
  X,
} from "lucide-react";
import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { toast } from "sonner";

import {
  type BindBlockState,
  type BindState,
  type EnumOption,
  buildBind,
  defaultFlagsFor,
  emptyBlock,
  extractEnumOptions,
  inferFlagType,
  KEY_GROUPS,
  newBlockId,
  validateBindState,
} from "@/lib/bind-builder";
import {
  type JbfCategory,
  type JbfCommand,
  JBF_CATEGORY_LABEL,
  JBF_COMMANDS,
  groupJbfCommands,
} from "@/lib/jbf-commands";
import { cn } from "@/lib/utils";

const GROUP_TONE_PER_CATEGORY: Record<JbfCategory, string> = {
  clear: "border-cyan/40 text-cyan",
  basic: "border-plasma/40 text-plasma",
};

/** Notes that hint the user about non-obvious flag semantics. Keyed by
 *  flag name, applied across all commands. */
const FLAG_NOTES: Record<string, string> = {
  "-g": "Aim = тот, кто под прицелом админа. Color = выдача по цвету формы (см. -c).",
  "-c": "Используется только когда -g = Color. Цвет команды/формы.",
  "-t": "0 или не указано — без таймера (до перезахода / снятия вручную).",
  "-cn": "Если 1 — действие будет видно в общем чате сервера.",
  "-b": "1 = включить эффект, 0 = выключить.",
};

export default function BindBuilderPage() {
  const [state, setState] = useState<BindState>(() => ({
    key: "",
    blocks: [emptyBlock()],
  }));
  const [showKeyboard, setShowKeyboard] = useState(false);

  const bindString = useMemo(
    () => buildBind(state, JBF_COMMANDS),
    [state],
  );
  const warnings = useMemo(() => validateBindState(state), [state]);

  // ── block ops ──────────────────────────────────────────────────────
  const updateBlock = useCallback(
    (id: string, mut: (b: BindBlockState) => BindBlockState) => {
      setState((s) => ({
        ...s,
        blocks: s.blocks.map((b) => (b.id === id ? mut(b) : b)),
      }));
    },
    [],
  );

  const addBlock = useCallback(() => {
    setState((s) => ({ ...s, blocks: [...s.blocks, emptyBlock()] }));
  }, []);

  const removeBlock = useCallback((id: string) => {
    setState((s) => ({
      ...s,
      blocks: s.blocks.length > 1 ? s.blocks.filter((b) => b.id !== id) : s.blocks,
    }));
  }, []);

  const moveBlock = useCallback((id: string, dir: -1 | 1) => {
    setState((s) => {
      const idx = s.blocks.findIndex((b) => b.id === id);
      if (idx < 0) return s;
      const j = idx + dir;
      if (j < 0 || j >= s.blocks.length) return s;
      const next = [...s.blocks];
      [next[idx], next[j]] = [next[j]!, next[idx]!];
      return { ...s, blocks: next };
    });
  }, []);

  const resetAll = useCallback(() => {
    if (!window.confirm("Очистить весь конструктор?")) return;
    setState({ key: "", blocks: [{ id: newBlockId(), cmd: "", flags: {} }] });
  }, []);

  // ── output actions ─────────────────────────────────────────────────
  const copyBind = useCallback(() => {
    if (!bindString) return;
    void navigator.clipboard.writeText(bindString).then(() => {
      toast.success("Скопировано в буфер");
    });
  }, [bindString]);

  const downloadCfg = useCallback(() => {
    if (!bindString) return;
    const cfg = `// jbf_uaio bind — generated by forum.innertalk.space\r\n${bindString}\r\n`;
    const blob = new Blob([cfg], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bind_${state.key || "key"}.cfg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Скачано как bind_*.cfg");
  }, [bindString, state.key]);

  return (
    <div className="container max-w-5xl py-6 md:py-10">
      <header className="mb-6">
        <div className="mb-2 flex items-center gap-2 text-[10px] uppercase tracking-widest text-smoke">
          <Link href="/" className="hover:text-ash">
            Главная
          </Link>
          <span>›</span>
          <span className="text-ash">Инструменты</span>
        </div>
        <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight text-bone">
          <Keyboard className="h-5 w-5 text-plasma" />
          Конструктор биндов jbf_uaio
        </h1>
        <p className="mt-1 max-w-3xl text-sm text-smoke">
          Выбираешь клавишу, собираешь цепочку команд админ-меню — на выходе
          готовая строка{" "}
          <code className="font-mono text-ash">bind &quot;…&quot; &quot;…&quot;</code>{" "}
          для копи-в-консоль или в твой{" "}
          <code className="font-mono text-ash">cstrike/userconfig.cfg</code>.
          Параметры взяты напрямую из ответа плагина (43 команды).
        </p>
        <p className="mt-1 text-xs text-smoke">
          Справочник всех флагов:{" "}
          <Link href="/admin/server-log" className="link-plasma">
            /admin/server-log → Справочник
          </Link>
        </p>
      </header>

      {/* ─── Key picker ───────────────────────────────────────── */}
      <section className="mb-6 rounded-lg border border-border bg-card/60 p-4">
        <div className="mb-3 flex items-baseline justify-between">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-bone">
            1. Клавиша
          </h2>
          {state.key && (
            <button
              type="button"
              onClick={() => setState((s) => ({ ...s, key: "" }))}
              className="text-[10px] text-smoke hover:text-ash"
            >
              сбросить
            </button>
          )}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <input
            type="text"
            value={state.key}
            onChange={(e) =>
              setState((s) => ({ ...s, key: e.target.value.toUpperCase() }))
            }
            placeholder="F5, KP_END, MOUSE3…"
            className="w-48 rounded-md border border-border bg-card px-3 py-2 font-mono text-sm text-bone outline-none transition-colors placeholder:text-smoke focus:border-plasma/60"
          />
          <button
            type="button"
            onClick={() => setShowKeyboard((v) => !v)}
            className={cn(
              "inline-flex h-9 items-center gap-1.5 rounded-md border px-3 text-xs transition-colors",
              showKeyboard
                ? "border-plasma/50 bg-plasma/10 text-plasma"
                : "border-border bg-card text-ash hover:border-plasma/40 hover:text-bone",
            )}
          >
            <ChevronDown
              className={cn("h-3 w-3 transition-transform", showKeyboard && "rotate-180")}
            />
            подсказки
          </button>
        </div>

        {showKeyboard && (
          <div className="mt-3 space-y-3">
            {KEY_GROUPS.map((g) => (
              <div key={g.label}>
                <div className="mb-1 text-[10px] uppercase tracking-widest text-smoke">
                  {g.label}
                </div>
                <div className="flex flex-wrap gap-1">
                  {g.keys.map((k) => (
                    <button
                      key={k}
                      type="button"
                      onClick={() => setState((s) => ({ ...s, key: k }))}
                      className={cn(
                        "rounded border px-1.5 py-0.5 font-mono text-[11px] transition-colors",
                        state.key === k
                          ? "border-plasma/60 bg-plasma/10 text-plasma"
                          : "border-border bg-card text-ash hover:border-plasma/40 hover:text-bone",
                      )}
                    >
                      {k}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* ─── Command chain ────────────────────────────────────── */}
      <section className="mb-6">
        <div className="mb-3 flex items-baseline justify-between">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-bone">
            2. Цепочка команд
          </h2>
          <button
            type="button"
            onClick={resetAll}
            className="inline-flex items-center gap-1 text-[10px] text-smoke hover:text-ember"
          >
            <Eraser className="h-3 w-3" />
            сбросить всё
          </button>
        </div>

        <div className="space-y-3">
          {state.blocks.map((block, idx) => (
            <CommandBlock
              key={block.id}
              block={block}
              index={idx}
              total={state.blocks.length}
              onChange={(mut) => updateBlock(block.id, mut)}
              onMoveUp={() => moveBlock(block.id, -1)}
              onMoveDown={() => moveBlock(block.id, 1)}
              onRemove={() => removeBlock(block.id)}
            />
          ))}
        </div>

        <button
          type="button"
          onClick={addBlock}
          className="mt-3 inline-flex items-center gap-1.5 rounded-md border border-dashed border-plasma/40 bg-plasma/5 px-3 py-2 text-xs text-plasma transition-colors hover:bg-plasma/10"
        >
          <Plus className="h-3.5 w-3.5" />
          Добавить команду
        </button>
      </section>

      {/* ─── Output ───────────────────────────────────────────── */}
      <section className="mb-6 rounded-lg border border-plasma/30 bg-plasma/5 p-4">
        <div className="mb-2 flex items-baseline justify-between">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-plasma">
            3. Готовая строка
          </h2>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={copyBind}
              disabled={!bindString}
              className="inline-flex h-7 items-center gap-1 rounded-md border border-plasma/40 bg-plasma/10 px-2.5 text-[11px] font-semibold text-plasma transition-colors hover:bg-plasma/20 disabled:cursor-not-allowed disabled:opacity-50"
            >
              <Copy className="h-3 w-3" />
              скопировать
            </button>
            <button
              type="button"
              onClick={downloadCfg}
              disabled={!bindString}
              className="inline-flex h-7 items-center gap-1 rounded-md border border-border bg-card px-2.5 text-[11px] text-ash transition-colors hover:border-plasma/40 hover:text-bone disabled:cursor-not-allowed disabled:opacity-50"
            >
              <Download className="h-3 w-3" />
              .cfg
            </button>
          </div>
        </div>
        <pre className="overflow-x-auto rounded-md border border-border bg-void/80 p-3 font-mono text-xs text-iridescent">
          {bindString || (
            <span className="text-smoke">
              {/* Show placeholder */}
              # bind &quot;…&quot; &quot;…&quot;{"\n"}# (добавь команды и
              выбери клавишу — строка соберётся здесь)
            </span>
          )}
        </pre>
        {warnings.length > 0 && (
          <ul className="mt-3 space-y-1">
            {warnings.map((w, i) => (
              <li
                key={i}
                className="rounded-md border border-flame/30 bg-flame/5 px-2 py-1 text-[11px] text-flame"
              >
                ⚠ {w}
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* ─── Howto ───────────────────────────────────────────── */}
      <section className="rounded-md border border-border bg-card/50 p-4 text-xs text-smoke">
        <h3 className="mb-2 text-[10px] uppercase tracking-widest text-ash">
          Куда вставить
        </h3>
        <ul className="space-y-1.5">
          <li>
            <strong className="text-ash">Вариант 1 — в файл:</strong> открой{" "}
            <code className="font-mono text-bone">cstrike/userconfig.cfg</code>{" "}
            (если файла нет — создай) и вставь сгенерированный bind. Перезайди
            на сервер — клавиша заработает.
          </li>
          <li>
            <strong className="text-ash">Вариант 2 — на сейчас:</strong> открой
            CS-консоль (~), вставь строку, нажми Enter. Бинд действует до выхода
            из игры.
          </li>
        </ul>
        <p className="mt-3 text-[11px] text-smoke">
          Команды требуют админских прав AMX-X на сервере — без них плагин
          молча проигнорирует. Aim в флаге{" "}
          <code className="font-mono text-ash">-g</code> = тот игрок, на
          которого ты сейчас смотришь.
        </p>
      </section>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────
// Command block
// ─────────────────────────────────────────────────────────────────────

function CommandBlock({
  block,
  index,
  total,
  onChange,
  onMoveUp,
  onMoveDown,
  onRemove,
}: {
  block: BindBlockState;
  index: number;
  total: number;
  onChange: (mut: (b: BindBlockState) => BindBlockState) => void;
  onMoveUp: () => void;
  onMoveDown: () => void;
  onRemove: () => void;
}) {
  const cmd = useMemo(
    () => JBF_COMMANDS.find((c) => c.cmd === block.cmd) ?? null,
    [block.cmd],
  );

  const setCmd = useCallback(
    (newCmd: string) => {
      const def = JBF_COMMANDS.find((c) => c.cmd === newCmd);
      onChange(() => ({
        id: block.id,
        cmd: newCmd,
        flags: def ? defaultFlagsFor(def) : {},
      }));
    },
    [block.id, onChange],
  );

  return (
    <div className="rounded-lg border border-border bg-card p-3">
      <div className="mb-2 flex items-center gap-2">
        <span className="font-mono text-[10px] text-smoke">#{index + 1}</span>
        <CommandPicker value={block.cmd} onChange={setCmd} />
        <div className="ml-auto flex items-center gap-0.5">
          <ActionBtn
            label="вверх"
            disabled={index === 0}
            onClick={onMoveUp}
            icon={<ArrowUp className="h-3 w-3" />}
          />
          <ActionBtn
            label="вниз"
            disabled={index === total - 1}
            onClick={onMoveDown}
            icon={<ArrowDown className="h-3 w-3" />}
          />
          <ActionBtn
            label="удалить блок"
            disabled={total === 1 && !block.cmd}
            onClick={onRemove}
            icon={<Trash2 className="h-3 w-3 text-ember" />}
          />
        </div>
      </div>

      {cmd ? (
        <FlagsTable cmd={cmd} block={block} onChange={onChange} />
      ) : (
        <p className="px-1 text-[11px] text-smoke">
          Выбери команду чтобы появились флаги ↑
        </p>
      )}
    </div>
  );
}

function ActionBtn({
  label,
  onClick,
  icon,
  disabled,
}: {
  label: string;
  onClick: () => void;
  icon: React.ReactNode;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      title={label}
      aria-label={label}
      className="inline-flex h-6 w-6 items-center justify-center rounded-md border border-border bg-card/80 text-smoke transition-colors hover:border-plasma/40 hover:text-bone disabled:cursor-not-allowed disabled:opacity-40"
    >
      {icon}
    </button>
  );
}

// ─────────────────────────────────────────────────────────────────────
// Command picker (searchable dropdown)
// ─────────────────────────────────────────────────────────────────────

function CommandPicker({
  value,
  onChange,
}: {
  value: string;
  onChange: (v: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const grouped = useMemo(() => groupJbfCommands(), []);
  const selected = useMemo(
    () => JBF_COMMANDS.find((c) => c.cmd === value),
    [value],
  );

  const filteredByCategory = useMemo(() => {
    const q = query.trim().toLowerCase();
    const out: Record<JbfCategory, JbfCommand[]> = { clear: [], basic: [] };
    for (const [cat, list] of Object.entries(grouped) as [JbfCategory, JbfCommand[]][]) {
      out[cat] = list.filter((c) =>
        !q ||
        c.cmd.toLowerCase().includes(q) ||
        c.label.toLowerCase().includes(q),
      );
    }
    return out;
  }, [grouped, query]);

  return (
    <div className="relative min-w-0 flex-1">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className={cn(
          "flex w-full min-w-0 items-center justify-between gap-2 rounded-md border bg-card px-3 py-1.5 text-left text-xs transition-colors",
          open
            ? "border-plasma/60"
            : "border-border hover:border-plasma/40",
        )}
      >
        <span className="flex min-w-0 items-baseline gap-2">
          <code className="truncate font-mono text-bone">
            {selected?.cmd ?? "выбрать команду…"}
          </code>
          {selected && (
            <span className="hidden truncate text-smoke sm:inline">
              {selected.label}
            </span>
          )}
        </span>
        <ChevronDown className={cn("h-3 w-3 shrink-0 transition-transform", open && "rotate-180")} />
      </button>

      {open && (
        <>
          {/* click-outside scrim */}
          <div
            className="fixed inset-0 z-30"
            onClick={() => setOpen(false)}
            aria-hidden="true"
          />
          <div className="absolute left-0 right-0 top-full z-40 mt-1 max-h-80 overflow-hidden rounded-md border border-border bg-card shadow-xl">
            <div className="flex items-center gap-2 border-b border-border px-2 py-1.5">
              <Search className="h-3.5 w-3.5 shrink-0 text-smoke" />
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="фильтр по cmd или лейблу…"
                autoFocus
                className="w-full bg-transparent text-xs text-bone outline-none placeholder:text-smoke"
              />
              {query && (
                <button
                  type="button"
                  onClick={() => setQuery("")}
                  className="text-smoke hover:text-bone"
                >
                  <X className="h-3 w-3" />
                </button>
              )}
            </div>
            <div className="max-h-64 overflow-y-auto">
              {(Object.keys(filteredByCategory) as JbfCategory[]).map((cat) => {
                const list = filteredByCategory[cat];
                if (list.length === 0) return null;
                return (
                  <div key={cat}>
                    <div
                      className={cn(
                        "border-b border-t border-border px-2 py-1 text-[9px] font-semibold uppercase tracking-widest",
                        GROUP_TONE_PER_CATEGORY[cat],
                      )}
                    >
                      {JBF_CATEGORY_LABEL[cat]} ({list.length})
                    </div>
                    {list.map((c) => (
                      <button
                        key={c.cmd}
                        type="button"
                        onClick={() => {
                          onChange(c.cmd);
                          setOpen(false);
                          setQuery("");
                        }}
                        className={cn(
                          "flex w-full items-baseline justify-between gap-2 px-3 py-1.5 text-left transition-colors hover:bg-slate",
                          c.cmd === value && "bg-slate",
                        )}
                      >
                        <span className="flex min-w-0 items-baseline gap-2">
                          <code className="truncate font-mono text-xs text-bone">
                            {c.cmd}
                          </code>
                          <span className="hidden truncate text-[11px] text-smoke sm:inline">
                            {c.label}
                          </span>
                        </span>
                        {c.cmd === value && (
                          <Check className="h-3 w-3 shrink-0 text-plasma" />
                        )}
                      </button>
                    ))}
                  </div>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────
// Flags table — renders per-flag inputs by inferred type
// ─────────────────────────────────────────────────────────────────────

function FlagsTable({
  cmd,
  block,
  onChange,
}: {
  cmd: JbfCommand;
  block: BindBlockState;
  onChange: (mut: (b: BindBlockState) => BindBlockState) => void;
}) {
  const setFlag = useCallback(
    (flag: string, mut: { enabled?: boolean; value?: string }) => {
      onChange((b) => ({
        ...b,
        flags: {
          ...b.flags,
          [flag]: {
            enabled: mut.enabled ?? b.flags[flag]?.enabled ?? false,
            value: mut.value ?? b.flags[flag]?.value ?? "",
          },
        },
      }));
    },
    [onChange],
  );

  return (
    <div className="space-y-1">
      <div className="rounded-md border border-border bg-void/30">
        {cmd.flags.map((f) => {
          const st = block.flags[f.flag] ?? { enabled: false, value: "" };
          const type = inferFlagType(f);
          const opts = type === "enum" ? extractEnumOptions(f) : [];
          const note = FLAG_NOTES[f.flag];

          return (
            <div
              key={f.flag}
              className={cn(
                "flex flex-wrap items-start gap-x-3 gap-y-1 border-b border-border px-2.5 py-1.5 last:border-b-0",
                !st.enabled && "opacity-60",
              )}
            >
              <label className="flex shrink-0 cursor-pointer items-center gap-1.5 pt-1">
                <input
                  type="checkbox"
                  checked={st.enabled}
                  onChange={(e) =>
                    setFlag(f.flag, { enabled: e.target.checked })
                  }
                  className="h-3 w-3 accent-plasma"
                />
                <code className="w-12 font-mono text-xs text-plasma">{f.flag}</code>
                <span className="text-[11px] text-ash">{f.label}</span>
              </label>

              <div className="flex min-w-0 flex-1 flex-wrap items-center gap-1.5">
                <FlagInput
                  type={type}
                  options={opts}
                  value={st.value}
                  enabled={st.enabled}
                  onValueChange={(value) => setFlag(f.flag, { enabled: true, value })}
                  placeholder={f.values ?? ""}
                />
              </div>

              {note && (
                <p className="mt-0.5 w-full pl-[68px] text-[10px] italic text-smoke">
                  {note}
                </p>
              )}
            </div>
          );
        })}
      </div>

      <p className="px-2 pt-1 text-[10px] text-smoke">
        Образец от плагина:{" "}
        <code className="font-mono text-ash">{cmd.example}</code>
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────
// Flag input — switches form by inferred type
// ─────────────────────────────────────────────────────────────────────

function FlagInput({
  type,
  options,
  value,
  enabled,
  onValueChange,
  placeholder,
}: {
  type: ReturnType<typeof inferFlagType>;
  options: EnumOption[];
  value: string;
  enabled: boolean;
  onValueChange: (v: string) => void;
  placeholder: string;
}) {
  if (type === "boolean") {
    const v = value === "1" || value === "0" ? value : "";
    return (
      <div className="flex items-center gap-3 text-[11px] text-ash">
        <label className="inline-flex cursor-pointer items-center gap-1">
          <input
            type="radio"
            checked={v === "1"}
            onChange={() => onValueChange("1")}
            disabled={!enabled}
            className="h-3 w-3 accent-plasma"
          />
          1 (вкл.)
        </label>
        <label className="inline-flex cursor-pointer items-center gap-1">
          <input
            type="radio"
            checked={v === "0"}
            onChange={() => onValueChange("0")}
            disabled={!enabled}
            className="h-3 w-3 accent-plasma"
          />
          0 (выкл.)
        </label>
      </div>
    );
  }

  if (type === "enum") {
    return (
      <select
        value={value}
        onChange={(e) => onValueChange(e.target.value)}
        disabled={!enabled}
        className="h-7 rounded border border-border bg-card px-2 font-mono text-xs text-bone outline-none focus:border-plasma/60 disabled:cursor-not-allowed"
      >
        <option value="">—</option>
        {options.map((o) => (
          <option key={o.value} value={o.value}>
            {o.value}
            {o.label && o.label !== o.value ? ` — ${o.label}` : ""}
          </option>
        ))}
      </select>
    );
  }

  if (type === "xyz" || type === "rgb") {
    return (
      <Triplet
        value={value}
        enabled={enabled}
        onChange={onValueChange}
        labels={type === "rgb" ? ["R", "G", "B"] : ["X", "Y", "Z"]}
        max={type === "rgb" ? 255 : undefined}
      />
    );
  }

  if (type === "number") {
    return (
      <input
        type="number"
        value={value}
        onChange={(e) => onValueChange(e.target.value)}
        disabled={!enabled}
        placeholder={placeholder}
        className="h-7 w-32 rounded border border-border bg-card px-2 font-mono text-xs text-bone outline-none placeholder:text-smoke/60 focus:border-plasma/60 disabled:cursor-not-allowed"
      />
    );
  }

  // text
  return (
    <input
      type="text"
      value={value}
      onChange={(e) => onValueChange(e.target.value)}
      disabled={!enabled}
      placeholder={placeholder}
      className="h-7 w-56 rounded border border-border bg-card px-2 font-mono text-xs text-bone outline-none placeholder:text-smoke/60 focus:border-plasma/60 disabled:cursor-not-allowed"
    />
  );
}

function Triplet({
  value,
  enabled,
  onChange,
  labels,
  max,
}: {
  value: string;
  enabled: boolean;
  onChange: (v: string) => void;
  labels: [string, string, string];
  max?: number;
}) {
  const parts = value.split(/\s+/).filter(Boolean);
  const v0 = parts[0] ?? "";
  const v1 = parts[1] ?? "";
  const v2 = parts[2] ?? "";
  const setAt = (i: 0 | 1 | 2, next: string) => {
    const arr = [v0, v1, v2];
    arr[i] = next;
    onChange(arr.filter(Boolean).join(" "));
  };
  return (
    <div className="flex items-center gap-1">
      {([v0, v1, v2] as const).map((v, i) => (
        <div key={i} className="flex items-center gap-1">
          <span className="text-[10px] text-smoke">{labels[i]}</span>
          <input
            type="number"
            value={v}
            onChange={(e) => setAt(i as 0 | 1 | 2, e.target.value)}
            disabled={!enabled}
            min={0}
            max={max}
            className="h-7 w-16 rounded border border-border bg-card px-1.5 font-mono text-xs text-bone outline-none focus:border-plasma/60 disabled:cursor-not-allowed"
          />
        </div>
      ))}
    </div>
  );
}
