"""Generate `cfg/uaio_usage_dump.cfg` for the CS 1.6 server.

When the user `exec`s the generated cfg in their CS console, the
jbf_uaio_modular plugin prints its usage block for each command. Each
block is wrapped between two echo delimiters
    ===JBF_CMD <slug>===
so the parser in parse_usage_dump.py can split the resulting condump
back into per-command chunks.

This is a one-shot tool — run locally, FTP the .cfg up, ask the user to
exec + condump, then FTP the dump back and run parse_usage_dump.py.

`SLUGS` mirrors frontend/src/lib/jbf-commands.ts. Keep them in sync.
"""
from __future__ import annotations

SLUGS = [
    # Clear
    "jbf_uaio_clear_basic",
    "jbf_uaio_clear_punitive",
    "jbf_uaio_clear_other",
    # Basic
    "jbf_uaio_respawn",
    "jbf_uaio_god",
    "jbf_uaio_noclip",
    "jbf_uaio_speed",
    "jbf_uaio_gravity",
    "jbf_uaio_invisibility",
    "jbf_uaio_antidamage",
    "jbf_uaio_teleport",
    "jbf_uaio_infinity_ammo",
    "jbf_uaio_infinity_bpammo",
    "jbf_uaio_infinity_he",
    "jbf_uaio_infinity_flash",
    "jbf_uaio_infinity_smoke",
    "jbf_uaio_glow",
    "jbf_uaio_hide_from_radar",
    "jbf_uaio_bhop",
    "jbf_uaio_double_jump",
    "jbf_uaio_silent_steps",
    "jbf_uaio_parachute",
    "jbf_uaio_microphone",
    "jbf_uaio_reload_logotip",
    "jbf_uaio_reload_ammo",
    "jbf_uaio_antirecoil",
    "jbf_uaio_edit_form",
    "jbf_uaio_kill",
    "jbf_uaio_freeze",
    "jbf_uaio_bury",
    "jbf_uaio_dealing_damage",
    "jbf_uaio_distortion_screen",
    "jbf_uaio_screen_color",
    "jbf_uaio_drugs",
    "jbf_uaio_slide",
    "jbf_uaio_earthquake",
    "jbf_uaio_disarm",
    "jbf_uaio_block_chat",
    "jbf_uaio_health",
    "jbf_uaio_give_weapon",
    "jbf_uaio_camera_view",
    "jbf_uaio_wallhack",
    "jbf_uaio_paint",
    "jbf_uaio_portal_gun",
    # Hit
    "jbf_uaio_hit_reload_ammo",
    "jbf_uaio_hit_god",
    "jbf_uaio_hit_noclip",
    "jbf_uaio_hit_speed",
    "jbf_uaio_hit_gravity",
    "jbf_uaio_hit_invisibility",
    "jbf_uaio_hit_antidamage",
    "jbf_uaio_hit_teleport",
    "jbf_uaio_hit_infinity_ammo",
    "jbf_uaio_hit_infinity_bpammo",
    "jbf_uaio_hit_infinity_he",
    "jbf_uaio_hit_infinity_flash",
    "jbf_uaio_hit_infinity_smoke",
    "jbf_uaio_hit_glow",
    "jbf_uaio_hit_hide_from_radar",
    "jbf_uaio_hit_bhop",
    "jbf_uaio_hit_double_jump",
    "jbf_uaio_hit_silent_steps",
    "jbf_uaio_hit_parachute",
    "jbf_uaio_hit_microphone",
    "jbf_uaio_hit_reload_logotip",
    "jbf_uaio_hit_antirecoil",
    "jbf_uaio_hit_repulsion",
    "jbf_uaio_hit_kill",
    "jbf_uaio_hit_freeze",
    "jbf_uaio_hit_bury",
    "jbf_uaio_hit_dealing_damage",
    "jbf_uaio_hit_distortion_screen",
    "jbf_uaio_hit_screen_color",
    "jbf_uaio_hit_drugs",
    "jbf_uaio_hit_slide",
    "jbf_uaio_hit_earthquake",
    "jbf_uaio_hit_disarm",
    "jbf_uaio_hit_health",
    "jbf_uaio_hit_give_weapon",
    "jbf_uaio_hit_camera_view",
    "jbf_uaio_hit_wallhack",
    "jbf_uaio_hit_edit_form",
    # Spike
    "jbf_uaio_spike_god",
    "jbf_uaio_spike_noclip",
    "jbf_uaio_spike_speed",
    "jbf_uaio_spike_gravity",
    "jbf_uaio_spike_invisibility",
    "jbf_uaio_spike_repulsion",
    "jbf_uaio_spike_freeze",
    "jbf_uaio_spike_edit_form",
    # Radius
    "jbf_uaio_radius_god",
    "jbf_uaio_radius_noclip",
    "jbf_uaio_radius_speed",
    "jbf_uaio_radius_gravity",
    "jbf_uaio_radius_invisibility",
    "jbf_uaio_radius_repulsion",
    "jbf_uaio_radius_dealing_damage",
    "jbf_uaio_radius_health",
    "jbf_uaio_radius_edit_form",
    # Grenade
    "jbf_uaio_grenade_speed",
    "jbf_uaio_grenade_teleport",
    "jbf_uaio_grenade_dealing_damage",
    "jbf_uaio_grenade_disarm",
    # Button
    "jbf_uaio_button_longjump",
    "jbf_uaio_button_speed",
    "jbf_uaio_button_teleport",
    # Kill
    "jbf_uaio_kill_vampirizm",
    # Kurator
    "jbf_uaio_kurator_uaio",
]


def build_cfg() -> str:
    lines = [
        "// Generated by forum.innertalk.space — jbf_uaio_modular usage dump.",
        "// Usage in CS 1.6 console:",
        "//   con_maxsize 65536",
        "//   exec uaio_usage_dump.cfg",
        "//   condump uaio_usage_dump.txt",
        "// The .txt drops into cstrike/uaio_usage_dump.txt — forum admin",
        "// grabs it via FTP.",
        "con_maxsize 65536",
        "echo ===JBF_BEGIN===",
    ]
    for slug in SLUGS:
        lines.append(f"echo ===JBF_CMD {slug}===")
        lines.append(slug)
    lines.append("echo ===JBF_END===")
    return "\r\n".join(lines) + "\r\n"


if __name__ == "__main__":
    import sys

    print(build_cfg(), end="")
    print(f"// {len(SLUGS)} commands", file=sys.stderr)
